import datetime
from dataclasses import dataclass, field

from modules.common.domain.timezone import get_current_datetime


@dataclass(frozen=True, kw_only=True)
class TrafficDTO:
    id: int | None = field(default=None)
    duration: str | None = field(default=None)
    protocol_type: str | None = field(default=None)
    service: str | None = field(default=None)
    flag: str | None = field(default=None)
    src_bytes: str | None = field(default=None)
    dst_bytes: str | None = field(default=None)
    land: str | None = field(default=None)
    wrong_fragment: str | None = field(default=None)
    urgent: str | None = field(default=None)
    hot: str | None = field(default=None)
    num_failed_logins: str | None = field(default=None)
    logged_in: str | None = field(default=None)
    num_compromised: str | None = field(default=None)
    root_shell: str | None = field(default=None)
    su_attempted: str | None = field(default=None)
    num_root: str | None = field(default=None)
    num_file_creations: str | None = field(default=None)
    num_shells: str | None = field(default=None)
    num_access_files: str | None = field(default=None)
    num_outbound_cmds: str | None = field(default=None)
    is_host_login: str | None = field(default=None)
    is_guest_login: str | None = field(default=None)
    count: str | None = field(default=None)
    srv_count: str | None = field(default=None)
    serror_rate: str | None = field(default=None)
    srv_serror_rate: str | None = field(default=None)
    rerror_rate: str | None = field(default=None)
    srv_rerror_rate: str | None = field(default=None)
    same_srv_rate: str | None = field(default=None)
    diff_srv_rate: str | None = field(default=None)
    srv_diff_host_rate: str | None = field(default=None)
    dst_host_count: str | None = field(default=None)
    dst_host_srv_count: str | None = field(default=None)
    dst_host_same_srv_rate: str | None = field(default=None)
    dst_host_diff_srv_rate: str | None = field(default=None)
    dst_host_same_src_port_rate: str | None = field(default=None)
    dst_host_srv_diff_host_rate: str | None = field(default=None)
    dst_host_serror_rate: str | None = field(default=None)
    dst_host_srv_serror_rate: str | None = field(default=None)
    dst_host_rerror_rate: str | None = field(default=None)
    dst_host_srv_rerror_rate: str | None = field(default=None)
    label: str | None = field(default=None)
    difficulty: str | None = field(default=None)
    created_at: datetime.datetime = field(default_factory=get_current_datetime)
