"""empty message

Revision ID: 5f492a38ce51
Revises: 
Create Date: 2024-04-13 03:08:44.466466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f492a38ce51"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "network_traffic",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("duration", sa.String(length=50), nullable=True),
        sa.Column("protocol_type", sa.String(length=50), nullable=True),
        sa.Column("service", sa.String(length=50), nullable=True),
        sa.Column("flag", sa.String(length=50), nullable=True),
        sa.Column("src_bytes", sa.String(length=50), nullable=True),
        sa.Column("dst_bytes", sa.String(length=50), nullable=True),
        sa.Column("land", sa.String(length=50), nullable=True),
        sa.Column("wrong_fragment", sa.String(length=50), nullable=True),
        sa.Column("urgent", sa.String(length=50), nullable=True),
        sa.Column("hot", sa.String(length=50), nullable=True),
        sa.Column("num_failed_logins", sa.String(length=50), nullable=True),
        sa.Column("logged_in", sa.String(length=50), nullable=True),
        sa.Column("num_compromised", sa.String(length=50), nullable=True),
        sa.Column("root_shell", sa.String(length=50), nullable=True),
        sa.Column("su_attempted", sa.String(length=50), nullable=True),
        sa.Column("num_root", sa.String(length=50), nullable=True),
        sa.Column("num_file_creations", sa.String(length=50), nullable=True),
        sa.Column("num_shells", sa.String(length=50), nullable=True),
        sa.Column("num_access_files", sa.String(length=50), nullable=True),
        sa.Column("num_outbound_cmds", sa.String(length=50), nullable=True),
        sa.Column("is_host_login", sa.String(length=50), nullable=True),
        sa.Column("is_guest_login", sa.String(length=50), nullable=True),
        sa.Column("count", sa.String(length=50), nullable=True),
        sa.Column("srv_count", sa.String(length=50), nullable=True),
        sa.Column("serror_rate", sa.String(length=50), nullable=True),
        sa.Column("srv_serror_rate", sa.String(length=50), nullable=True),
        sa.Column("rerror_rate", sa.String(length=50), nullable=True),
        sa.Column("srv_rerror_rate", sa.String(length=50), nullable=True),
        sa.Column("same_srv_rate", sa.String(length=50), nullable=True),
        sa.Column("diff_srv_rate", sa.String(length=50), nullable=True),
        sa.Column("srv_diff_host_rate", sa.String(length=50), nullable=True),
        sa.Column("dst_host_count", sa.String(length=50), nullable=True),
        sa.Column("dst_host_srv_count", sa.String(length=50), nullable=True),
        sa.Column("dst_host_same_srv_rate", sa.String(length=50), nullable=True),
        sa.Column("dst_host_diff_srv_rate", sa.String(length=50), nullable=True),
        sa.Column("dst_host_same_src_port_rate", sa.String(length=50), nullable=True),
        sa.Column("dst_host_srv_diff_host_rate", sa.String(length=50), nullable=True),
        sa.Column("dst_host_serror_rate", sa.String(length=50), nullable=True),
        sa.Column("dst_host_srv_serror_rate", sa.String(length=50), nullable=True),
        sa.Column("dst_host_rerror_rate", sa.String(length=50), nullable=True),
        sa.Column("dst_host_srv_rerror_rate", sa.String(length=50), nullable=True),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("difficulty", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("network_traffic")
    # ### end Alembic commands ###
