"""empty message

Revision ID: b988d80825f2
Revises: 5f492a38ce51
Create Date: 2024-04-13 18:11:17.119738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b988d80825f2"
down_revision: Union[str, None] = "5f492a38ce51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "network_traffic",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("network_traffic", "created_at")
    # ### end Alembic commands ###
